name: Build

on:
  workflow_run:
    workflows: [Validate]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Push to Docker image to GitHub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata (tags, labels)
        id: meta-node-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/node-api
          labels: |
            org.opencontainers.image.title=node-api
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta-node-api.outputs.tags }}
          labels: ${{ steps.meta-node-api.outputs.labels }}

#      - name: Import Secrets
#          id: import-secrets
#          uses: hashicorp/vault-action@v2
#          with:
#            url: https://vault.myuoj.xyz
#            method: approle
#            roleId: ${{ secrets.VAULT_ROLE_ID }}
#            secretId: ${{ secrets.VAULT_SECRET_ID }}
#            secrets: |
#              secret/data/services/admission  *