name: DevServerDeployer

on:
  workflow_run:
    workflows: [BuildExecutor]
    types:
      - completed

jobs:
  build:
    name: Dev Server Deployer Job
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


