name: Build Pipeline

on:
  push:
    branches: [DEVELOP]
  pull_request:
    branches: [DEVELOP]
    tags:
      - v**


  jobs:
    build:
      include:
        - .github/workflows/validate.yml
        - .github/workflows/build.yaml
