name: CI/CD Pipeline

on:
  push:
    branches: [ "DEVELOP" ]
    tags:
      - v**
  pull_request:
    branches: [ "DEVELOP" ]
    tags:
      - v**

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  build:
    uses: ./.github/workflows/build.yml
