name: CI/CD Pipeline

on:
  push:
    branches: [ "DEVELOP" ]
    tags:
      - v**
  pull_request:
    branches: [ "DEVELOP" ]
    tags:
      - v**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  build:
    uses: ./.github/workflows/build.yml
