name: TestRunner

on:
  push:
    branches: [ "DEVELOP" ]
    tags:
      - v**
  pull_request:
    branches: [ "DEVELOP" ]
    tags:
      - v**

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./api